// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/sg/api/v1/mesh.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Mesh struct {
	// Status indicates the validation status of this resource.
	// Status is read-only by clients, and set by supergloo during validation
	Status core.Status `protobuf:"bytes,100,opt,name=status,proto3" json:"status" testdiff:"ignore"`
	// Metadata contains the object metadata for this resource
	Metadata             core.Metadata `protobuf:"bytes,101,opt,name=metadata,proto3" json:"metadata"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Mesh) Reset()         { *m = Mesh{} }
func (m *Mesh) String() string { return proto.CompactTextString(m) }
func (*Mesh) ProtoMessage()    {}
func (*Mesh) Descriptor() ([]byte, []int) {
	return fileDescriptor_50bb8d41d8087825, []int{0}
}
func (m *Mesh) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Mesh.Unmarshal(m, b)
}
func (m *Mesh) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Mesh.Marshal(b, m, deterministic)
}
func (m *Mesh) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Mesh.Merge(m, src)
}
func (m *Mesh) XXX_Size() int {
	return xxx_messageInfo_Mesh.Size(m)
}
func (m *Mesh) XXX_DiscardUnknown() {
	xxx_messageInfo_Mesh.DiscardUnknown(m)
}

var xxx_messageInfo_Mesh proto.InternalMessageInfo

func (m *Mesh) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *Mesh) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

type MeshGroup struct {
	// Status indicates the validation status of this resource.
	// Status is read-only by clients, and set by supergloo during validation
	Status core.Status `protobuf:"bytes,100,opt,name=status,proto3" json:"status" testdiff:"ignore"`
	// Metadata contains the object metadata for this resource
	Metadata core.Metadata `protobuf:"bytes,101,opt,name=metadata,proto3" json:"metadata"`
	// the meshes contained in this group
	Meshes               []*core.ResourceRef `protobuf:"bytes,3,rep,name=meshes,proto3" json:"meshes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MeshGroup) Reset()         { *m = MeshGroup{} }
func (m *MeshGroup) String() string { return proto.CompactTextString(m) }
func (*MeshGroup) ProtoMessage()    {}
func (*MeshGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_50bb8d41d8087825, []int{1}
}
func (m *MeshGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshGroup.Unmarshal(m, b)
}
func (m *MeshGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshGroup.Marshal(b, m, deterministic)
}
func (m *MeshGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshGroup.Merge(m, src)
}
func (m *MeshGroup) XXX_Size() int {
	return xxx_messageInfo_MeshGroup.Size(m)
}
func (m *MeshGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshGroup.DiscardUnknown(m)
}

var xxx_messageInfo_MeshGroup proto.InternalMessageInfo

func (m *MeshGroup) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *MeshGroup) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *MeshGroup) GetMeshes() []*core.ResourceRef {
	if m != nil {
		return m.Meshes
	}
	return nil
}

func init() {
	proto.RegisterType((*Mesh)(nil), "sg.solo.io.Mesh")
	proto.RegisterType((*MeshGroup)(nil), "sg.solo.io.MeshGroup")
}

func init() {
	proto.RegisterFile("github.com/solo-io/sg/api/v1/mesh.proto", fileDescriptor_50bb8d41d8087825)
}

var fileDescriptor_50bb8d41d8087825 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x52, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xfe, 0xfb, 0xd3, 0x10, 0x5c, 0xbc, 0x58, 0x89, 0x29, 0x1c, 0x80, 0xf4, 0xa0, 0x1c, 0xb4,
	0x1b, 0xf0, 0x62, 0x38, 0x72, 0xe1, 0xc4, 0xa5, 0xde, 0xbc, 0x2d, 0x74, 0xba, 0x6c, 0xa0, 0x4c,
	0xb3, 0xbb, 0xd5, 0x7b, 0x1f, 0xc4, 0xb3, 0x8f, 0xe2, 0x3b, 0x98, 0x70, 0xf0, 0x0d, 0xea, 0x13,
	0x98, 0x2d, 0xad, 0x86, 0x04, 0x13, 0xbc, 0x79, 0x6a, 0x67, 0xbe, 0xef, 0x9b, 0xf9, 0x66, 0x67,
	0xc8, 0x15, 0x17, 0x7a, 0x99, 0xce, 0xfd, 0x05, 0xc6, 0x54, 0xe1, 0x1a, 0x6f, 0x04, 0x52, 0xc5,
	0x29, 0x4b, 0x04, 0x7d, 0x1c, 0xd2, 0x18, 0xd4, 0xd2, 0x4f, 0x24, 0x6a, 0x74, 0x88, 0xe2, 0xbe,
	0x21, 0xf8, 0x02, 0x3b, 0x2d, 0x8e, 0x1c, 0x8b, 0x34, 0x35, 0x7f, 0x3b, 0x46, 0xa7, 0xcb, 0x11,
	0xf9, 0x1a, 0x68, 0x11, 0xcd, 0xd3, 0x88, 0x86, 0xa9, 0x64, 0x5a, 0xe0, 0xe6, 0x27, 0xfc, 0x49,
	0xb2, 0x24, 0x01, 0xa9, 0x4a, 0x7c, 0x78, 0xc8, 0x8a, 0xf9, 0xae, 0x84, 0xfe, 0x36, 0xa4, 0x59,
	0xc8, 0x34, 0x2b, 0x25, 0xf4, 0x08, 0x89, 0xd2, 0x4c, 0xa7, 0x55, 0x8f, 0xeb, 0x23, 0x04, 0x12,
	0xa2, 0x5f, 0x38, 0xaa, 0xe2, 0x9d, 0xc4, 0x7b, 0xb6, 0x88, 0x3d, 0x03, 0xb5, 0x74, 0xa6, 0xa4,
	0xbe, 0xeb, 0xec, 0x86, 0x7d, 0x6b, 0xd0, 0x1c, 0xb5, 0xfc, 0x05, 0x4a, 0xa8, 0x9e, 0xd0, 0xbf,
	0x2f, 0xb0, 0x49, 0xfb, 0x75, 0xdb, 0xfb, 0xf7, 0xb1, 0xed, 0x9d, 0x69, 0x50, 0x3a, 0x14, 0x51,
	0x34, 0xf6, 0x04, 0xdf, 0xa0, 0x04, 0x2f, 0x28, 0xe5, 0xce, 0x1d, 0x69, 0x54, 0x53, 0xbb, 0x50,
	0x94, 0xba, 0xd8, 0x2f, 0x35, 0x2b, 0xd1, 0x89, 0x6d, 0x8a, 0x05, 0x5f, 0xec, 0xf1, 0x79, 0x96,
	0xdb, 0x35, 0x62, 0xc5, 0x59, 0x6e, 0x37, 0x9c, 0xba, 0xd9, 0x25, 0x28, 0xef, 0xcd, 0x22, 0x27,
	0xc6, 0xe0, 0x54, 0x62, 0x9a, 0xfc, 0x01, 0x97, 0xce, 0x90, 0x94, 0xd6, 0xdc, 0x5a, 0xbf, 0x36,
	0x68, 0x8e, 0xda, 0xfb, 0xba, 0x00, 0x14, 0xa6, 0x72, 0x01, 0x01, 0x44, 0x41, 0x49, 0x1c, 0xbb,
	0x59, 0x6e, 0xdb, 0xe4, 0x7f, 0xcc, 0xb3, 0xdc, 0x3e, 0x75, 0x88, 0xc9, 0x72, 0x33, 0x8e, 0x9a,
	0x5c, 0xbe, 0xbc, 0x77, 0xad, 0x87, 0xfe, 0xe1, 0xa3, 0x4e, 0x56, 0xd5, 0x61, 0xcf, 0xeb, 0xc5,
	0xb6, 0x6e, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x48, 0xca, 0x52, 0x15, 0xff, 0x02, 0x00, 0x00,
}

func (this *Mesh) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Mesh)
	if !ok {
		that2, ok := that.(Mesh)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *MeshGroup) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*MeshGroup)
	if !ok {
		that2, ok := that.(MeshGroup)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if len(this.Meshes) != len(that1.Meshes) {
		return false
	}
	for i := range this.Meshes {
		if !this.Meshes[i].Equal(that1.Meshes[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
