// Code generated by solo-kit. DO NOT EDIT.

// +build solokit

package v1

import (
	"context"
	"sync"
	"time"

	istio_networking_v1alpha3 "github.com/solo-io/sg/pkg/api/external/istio/networking/v1alpha3"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/factory"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients/memory"
)

var _ = Describe("RoutingEventLoop", func() {
	var (
		namespace string
		emitter   RoutingEmitter
		err       error
	)

	BeforeEach(func() {

		routingRuleClientFactory := &factory.MemoryResourceClientFactory{
			Cache: memory.NewInMemoryResourceCache(),
		}
		routingRuleClient, err := NewRoutingRuleClient(routingRuleClientFactory)
		Expect(err).NotTo(HaveOccurred())

		destinationRuleClientFactory := &factory.MemoryResourceClientFactory{
			Cache: memory.NewInMemoryResourceCache(),
		}
		destinationRuleClient, err := istio_networking_v1alpha3.NewDestinationRuleClient(destinationRuleClientFactory)
		Expect(err).NotTo(HaveOccurred())

		virtualServiceClientFactory := &factory.MemoryResourceClientFactory{
			Cache: memory.NewInMemoryResourceCache(),
		}
		virtualServiceClient, err := istio_networking_v1alpha3.NewVirtualServiceClient(virtualServiceClientFactory)
		Expect(err).NotTo(HaveOccurred())

		emitter = NewRoutingEmitter(routingRuleClient, destinationRuleClient, virtualServiceClient)
	})
	It("runs sync function on a new snapshot", func() {
		_, err = emitter.RoutingRule().Write(NewRoutingRule(namespace, "jerry"), clients.WriteOpts{})
		Expect(err).NotTo(HaveOccurred())
		_, err = emitter.DestinationRule().Write(istio_networking_v1alpha3.NewDestinationRule(namespace, "jerry"), clients.WriteOpts{})
		Expect(err).NotTo(HaveOccurred())
		_, err = emitter.VirtualService().Write(istio_networking_v1alpha3.NewVirtualService(namespace, "jerry"), clients.WriteOpts{})
		Expect(err).NotTo(HaveOccurred())
		sync := &mockRoutingSyncer{}
		el := NewRoutingEventLoop(emitter, sync)
		_, err := el.Run([]string{namespace}, clients.WatchOpts{})
		Expect(err).NotTo(HaveOccurred())
		Eventually(sync.Synced, 5*time.Second).Should(BeTrue())
	})
})

type mockRoutingSyncer struct {
	synced bool
	mutex  sync.Mutex
}

func (s *mockRoutingSyncer) Synced() bool {
	s.mutex.Lock()
	defer s.mutex.Unlock()
	return s.synced
}

func (s *mockRoutingSyncer) Sync(ctx context.Context, snap *RoutingSnapshot) error {
	s.mutex.Lock()
	s.synced = true
	s.mutex.Unlock()
	return nil
}
